audit_header: false
title: Rancho Cucamonga Real Estate Video Blog with Maria Diaz
description: Our mission at Intero Real Estate is to be your best resource for Rancho Cucamonga real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Intero Real Estate, your professional Rancho Cucamonga Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Maria Diaz
  title:
  license_number:
  about_markdown: |
    Maria Diaz has the success to overcome obstacles when it comes to selling your home. She has sold many homes for over the list price because she excels to negotiate over the asking price.
  market: Rancho Cucamonga
  brand: Intero Real Estate
  brokerage:
  address: 26440 La Alameda 250, Mission Viejo, CA 92691
  phone: 951-591-0413
  phone_type:
  phone2:
  phone2_type:
  email: mariadiazrealestate@gmail.com
  url: http://MariaDiazRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your Rancho Cucamonga Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a Rancho Cucamonga Home?"
    CTA_text2: "Search the entire MLS for your Rancho Cucamonga home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/MariaDiazRealEstate/
  linkedin_url:
  gplus_url: https://plus.google.com/u/0/109908182814217586903
  youtube_url: https://www.youtube.com/channel/UCQ3gjBvQkjBcnFlWy_yNrVA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/MariaDiazRealEstate/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Rancho Cucamonga Real Estate Podcast with Maria Diaz'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Rancho Cucamonga Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Intero Real Estate - your professional Rancho Cucamonga Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Rancho Cucamonga, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Maria Diaz'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Rancho Cucamonga Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#650336'
  theme_color: '#363636'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(101, 3, 54, .75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
